---
- name: Converge Nautobot 2.x
  hosts: all
  become: true
  vars:
    nginx__port_http: 8080
    nginx__port_https: 8443
    nginx__network: 'test_nginx_network'
    nginx__network_cidr: '172.16.23.0/24'
    nginx__remove_existing_container: true
    nginx__remove_existing_home_dir: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: bsmeding.docker
    - role: bsmeding.nginx_docker
