---
- name: Converge
  hosts: all
  gather_facts: false

  vars:
    molecule_nginx_home: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/.molecule/nginx"
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx__port_http: 18080
    nginx__port_https: 18443
    nginx__ports:
      - "{{ nginx__port_http }}:80"
      - "{{ nginx__port_https }}:443"
    nginx_vhosts:
      - server_name: "test.dev"
        root: "/var/www/test"

  pre_tasks:
    - name: Ensure remote tmp exists on instance
      ansible.builtin.raw: mkdir -p /tmp/.ansible && chmod 0777 /tmp/.ansible

    - name: Gather facts
      ansible.builtin.setup:

    - name: Override nginx paths for Molecule workspace
      ansible.builtin.set_fact:
        nginx__home: "{{ molecule_nginx_home }}"
        nginx__directory_volumes:
          - "{{ molecule_nginx_home }}/config:/config"
          - "{{ molecule_nginx_home }}/www:/var/www"
        nginx__file_volumes: []

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

  roles:
    - role: bsmeding.nginx_docker
