---
- name: Converge
  hosts: all

  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx__port_http: 8080
    nginx__port_https: 8443
    nginx__ports:
      - "{{ nginx__port_http }}:80"
      - "{{ nginx__port_https }}:443"
    nginx_vhosts:
      - server_name: "test.dev"
        root: "/var/www/test"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

  roles:
    - role: bsmeding.nginx_docker
