---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
driver:
  name: docker
platforms:
  - name: instance
    image: "bsmeding/ansible_cicd_${MOLECULE_DISTRO:-debian12}:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /run
      - /run/lock
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ${MOLECULE_PLAYBOOK_PREPARE:-prepare.yml}
    create: ${MOLECULE_PLAYBOOK_CREATE:-create.yml}
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_PLAYBOOK_VERIFY:-verify.yml}
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
