---
- name: Verify - Nginx is running
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - "yml"

    - name: Check that if default page is running
      ansible.builtin.uri:
        url: "http://localhost:8080"
        return_content: true
      register: local_webserver_output
      failed_when: local_webserver_output is failed or local_webserver_output.status != 200
      # or "'Welcome to our server' not in local_webserver_output.content"

    - name: Show output
      debug:
        var: local_webserver_output

    - name: Verify nginx container is running
      community.docker.docker_container_info:
        name: "{{ nginx__name }}"
      register: nginx_container_info

    - name: Check nginx container status
      assert:
        that:
          - nginx_container_info.exists
          - nginx_container_info.container.State.Status == "running"
        fail_msg: "Nginx container is not running"
