---
- name: Verify Nginx Docker role
  hosts: all
  become: true
  vars:
    molecule_nginx_home: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') | default('/tmp/molecule', true) }}/nginx"
    molecule_nginx_http_port: 18080
    molecule_nginx_https_port: 18443
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Set molecule testing ports
      ansible.builtin.set_fact:
        nginx__home: "{{ molecule_nginx_home }}"
        nginx__port_http: "{{ molecule_nginx_http_port }}"
        nginx__port_https: "{{ molecule_nginx_https_port }}"
        nginx__directory_volumes:
          - "{{ molecule_nginx_home }}/config:/config"
          - "{{ molecule_nginx_home }}/www:/var/www"
        nginx__file_volumes: []

    - name: "Wait for Nginx HTTP port {{ nginx__port_http }} to come active"
      ansible.builtin.command: >
        docker exec {{ nginx__name }} curl -fsS http://127.0.0.1:80
      register: nginx_http_ready
      retries: 40
      delay: 3
      until: nginx_http_ready.rc == 0
      changed_when: false

    - name: Gather container info
      community.docker.docker_container_info:
        name: "{{ nginx__name }}"
      register: nginx_container
      failed_when: false

    - name: Ensure container exists
      ansible.builtin.fail:
        msg: "Container {{ nginx__name }} not found"
      when: nginx_container.container is not defined

    - name: Assert container is running
      ansible.builtin.assert:
        that:
          - nginx_container.container.State.Running | default(false)
        fail_msg: "Container {{ nginx__name }} is not running"

    - name: Check HTTP endpoint responds
      ansible.builtin.command: >
        docker exec {{ nginx__name }} curl -fsS -o /dev/null http://127.0.0.1:80
      register: nginx_http
      retries: 20
      delay: 3
      until: nginx_http.rc == 0
      changed_when: false
